services:
  backend:
    container_name: aatmun-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./static:/code/static
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - aatmun

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    # pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - aatmun

networks:
  aatmun:
    external: false