from typing_extensions import List, TypedDict
from langchain_core.documents import Document
from app import rag, llm, schema
from langgraph.graph import START, StateGraph


class State(TypedDict):
    """
    Represents the state of the graph.

    Attributes:
        question (str): The question being asked.
        context (List[Document]): A list of documents retrieved from the vector store.
        navigation (schema.Navigation): The navigation information generated by the model.
    """
    question: str
    context: List[Document]
    navigation: schema.Navigation


def retrieve(state: State):
    """
    Retrieves documents from the vector store based on the question in the state.

    Args:
        state (State): The current state of the graph.

    Returns:
        dict: A dictionary containing the retrieved documents in the 'context' key.
    """
    vectorstore = rag.get_vectorstore()
    retriever = vectorstore.as_retriever()
    retrieved_docs = retriever.invoke(input=state["question"])
    return {"context": retrieved_docs}


def generate(state: State):
    """
    Generates a navigation response based on the retrieved context and the question.

    Args:
        state (State): The current state of the graph.

    Returns:
        dict: A dictionary containing the generated navigation information in the 'navigation' key.
    """
    context = ""
    id_mapping = {}

    for i, doc in enumerate(state["context"], start=1):
        id_mapping[i] = doc.id
        context += f"{i} - {doc.page_content} | "
    try:
        response = llm.rag_chain.invoke(
            {"query": state["question"], "context": context}
        )
        if response:
            id = response.id
            response.id = id_mapping.get(id, None)
            return {"navigation": response}
    except Exception as e:
        print(f"Failed to get Navigation due to: {e}")


graph_builder = StateGraph(State).add_sequence([retrieve, generate])
graph_builder.add_edge(START, "retrieve")
graph = graph_builder.compile()
